---
version: '2'
services:
  deskpro-fpm:
    build: fpm
    depends_on:
      - mariadb
      - deskpro-fpm-cron
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USER: deskprouser
      MYSQL_PASSWORD: deskpropassword
      MYSQL_DATABASE: deskprodb
    volumes:
      - deskpro-fpm:/var/www/html
  deskpro-fpm-cron:
    build: fpm
    command: deskpro-docker-cron
    depends_on:
      - mariadb
    volumes:
      - deskpro-fpm:/var/www/html
  deskpro-fpm-nginx:
    depends_on:
      - deskpro-fpm
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro,z
      - deskpro-fpm:/var/www/html:ro
  mariadb:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
      MYSQL_DATABASE: deskprodb
      MYSQL_USER: deskprouser
      MYSQL_PASSWORD: deskpropassword
volumes:
  deskpro-fpm:
